/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tenda;

import java.util.HashSet;
import javax.swing.JOptionPane;
/**
 *
 * @author david
 */
public class frmMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmMenu.class.getName());

    int Privilegios;
    frmAcercaDe PantAcercaDe;
    
    /**
     * Creates new form Menu
     */
    public frmMenu(int nivel) {
        
        Privilegios = nivel;
        
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        if(Privilegios == 1){
            mnuAdministracion.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContenedor = new javax.swing.JPanel();
        jMenuBar2 = new javax.swing.JMenuBar();
        mnuSesion = new javax.swing.JMenu();
        mnubtnCerrarSesion = new javax.swing.JMenuItem();
        mnubtnSalir = new javax.swing.JMenuItem();
        mnuVentas = new javax.swing.JMenu();
        mnubtnRealizarVenta = new javax.swing.JMenuItem();
        mnubtnConsultarMenu = new javax.swing.JMenuItem();
        mnubtnConsultarPromociones = new javax.swing.JMenuItem();
        mnuAyuda = new javax.swing.JMenu();
        mnubtnAyudaVentas = new javax.swing.JMenuItem();
        mnubtnAyudaAdmin = new javax.swing.JMenuItem();
        mnubtnAcercade = new javax.swing.JMenuItem();
        mnuAdministracion = new javax.swing.JMenu();
        mnubtnPromociones = new javax.swing.JMenuItem();
        sbmnuEmpleados = new javax.swing.JMenu();
        mnubtnRegistrarEmpleado = new javax.swing.JMenuItem();
        mnubtnModificarEmpleado = new javax.swing.JMenuItem();
        mnubtnDespedirEmpleado = new javax.swing.JMenuItem();
        mnubtnConsultarRegistros = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout pnlContenedorLayout = new javax.swing.GroupLayout(pnlContenedor);
        pnlContenedor.setLayout(pnlContenedorLayout);
        pnlContenedorLayout.setHorizontalGroup(
            pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 791, Short.MAX_VALUE)
        );
        pnlContenedorLayout.setVerticalGroup(
            pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 442, Short.MAX_VALUE)
        );

        mnuSesion.setText("Sesion");

        mnubtnCerrarSesion.setText("Cerrar sesion");
        mnubtnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnubtnCerrarSesionActionPerformed(evt);
            }
        });
        mnuSesion.add(mnubtnCerrarSesion);

        mnubtnSalir.setText("Salir");
        mnubtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnubtnSalirActionPerformed(evt);
            }
        });
        mnuSesion.add(mnubtnSalir);

        jMenuBar2.add(mnuSesion);

        mnuVentas.setText("Ventas");

        mnubtnRealizarVenta.setText("Realizar ventas");
        mnubtnRealizarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnubtnRealizarVentaActionPerformed(evt);
            }
        });
        mnuVentas.add(mnubtnRealizarVenta);

        mnubtnConsultarMenu.setText("Consultar menu");
        mnubtnConsultarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnubtnConsultarMenuActionPerformed(evt);
            }
        });
        mnuVentas.add(mnubtnConsultarMenu);

        mnubtnConsultarPromociones.setText("Consultar promociones");
        mnuVentas.add(mnubtnConsultarPromociones);

        jMenuBar2.add(mnuVentas);

        mnuAyuda.setText("Ayuda");

        mnubtnAyudaVentas.setText("Ayuda ventas");
        mnuAyuda.add(mnubtnAyudaVentas);

        mnubtnAyudaAdmin.setText("Ayuda administracion");
        mnuAyuda.add(mnubtnAyudaAdmin);

        mnubtnAcercade.setText("Acerca de...");
        mnubtnAcercade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnubtnAcercadeActionPerformed(evt);
            }
        });
        mnuAyuda.add(mnubtnAcercade);

        jMenuBar2.add(mnuAyuda);

        mnuAdministracion.setText("Administracion");
        mnuAdministracion.setEnabled(false);

        mnubtnPromociones.setText("Promociones");
        mnuAdministracion.add(mnubtnPromociones);

        sbmnuEmpleados.setText("Empleados");

        mnubtnRegistrarEmpleado.setText("Registrar empleado");
        mnubtnRegistrarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnubtnRegistrarEmpleadoActionPerformed(evt);
            }
        });
        sbmnuEmpleados.add(mnubtnRegistrarEmpleado);

        mnubtnModificarEmpleado.setText("Modificar empleado");
        sbmnuEmpleados.add(mnubtnModificarEmpleado);

        mnubtnDespedirEmpleado.setText("Despedir empleado");
        sbmnuEmpleados.add(mnubtnDespedirEmpleado);

        mnuAdministracion.add(sbmnuEmpleados);

        mnubtnConsultarRegistros.setText("Consultar registro de ventas");
        mnuAdministracion.add(mnubtnConsultarRegistros);

        jMenuBar2.add(mnuAdministracion);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnubtnConsultarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnubtnConsultarMenuActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_mnubtnConsultarMenuActionPerformed

    private void mnubtnAcercadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnubtnAcercadeActionPerformed
        // TODO add your handling code here:
        frmAcercaDe AcercaDe = new frmAcercaDe();
        AcercaDe.setVisible(true);
        
    }//GEN-LAST:event_mnubtnAcercadeActionPerformed

    private void mnubtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnubtnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnubtnSalirActionPerformed

    private void mnubtnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnubtnCerrarSesionActionPerformed
        // TODO add your handling code here:
        int respuesta = JOptionPane.showConfirmDialog(this,"¿Cerrar Sesion?","Confirmación de Cierre de Sesión",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (respuesta == JOptionPane.YES_OPTION) {
            
            frmLogin newLogin = new frmLogin();
            newLogin.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_mnubtnCerrarSesionActionPerformed

    private void mnubtnRegistrarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnubtnRegistrarEmpleadoActionPerformed
        frmInternalRegistroEmpleado RegistroEmpleado = new frmInternalRegistroEmpleado();
        pnlContenedor.add(RegistroEmpleado);
        RegistroEmpleado.setVisible(true);
    }//GEN-LAST:event_mnubtnRegistrarEmpleadoActionPerformed

    private void mnubtnRealizarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnubtnRealizarVentaActionPerformed
        // TODO add your handling code here:
        pnlVenta Venta = new pnlVenta();

        pnlContenedor.add(Venta);
        Venta.setVisible(true);
    }//GEN-LAST:event_mnubtnRealizarVentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new frmMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu mnuAdministracion;
    private javax.swing.JMenu mnuAyuda;
    private javax.swing.JMenu mnuSesion;
    private javax.swing.JMenu mnuVentas;
    private javax.swing.JMenuItem mnubtnAcercade;
    private javax.swing.JMenuItem mnubtnAyudaAdmin;
    private javax.swing.JMenuItem mnubtnAyudaVentas;
    private javax.swing.JMenuItem mnubtnCerrarSesion;
    private javax.swing.JMenuItem mnubtnConsultarMenu;
    private javax.swing.JMenuItem mnubtnConsultarPromociones;
    private javax.swing.JMenuItem mnubtnConsultarRegistros;
    private javax.swing.JMenuItem mnubtnDespedirEmpleado;
    private javax.swing.JMenuItem mnubtnModificarEmpleado;
    private javax.swing.JMenuItem mnubtnPromociones;
    private javax.swing.JMenuItem mnubtnRealizarVenta;
    private javax.swing.JMenuItem mnubtnRegistrarEmpleado;
    private javax.swing.JMenuItem mnubtnSalir;
    private javax.swing.JPanel pnlContenedor;
    private javax.swing.JMenu sbmnuEmpleados;
    // End of variables declaration//GEN-END:variables
}
