/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package tenda;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author david
 */
public class pnlConsultaMenu extends javax.swing.JInternalFrame {

    private DefaultTableModel ModeloMenu;
    private File ArchivoMenu;
    
    /**
     * Creates new form pnlConsultaMenu
     */
    
    public pnlConsultaMenu() {
        initComponents();
        
        ModeloMenu = (DefaultTableModel)tblMenu.getModel();
        
        ArchivoMenu = new File("Menu.txt");
        
        if(ArchivoMenu.exists()){
            CargarDatos();
        }
    }
    
    private void CargarDatos(){
        int ID;
        String Nombre;
        String Descripcion;
        String Categoria;
        String Tamano;
        Float Precio;
        boolean Disponibilidad;
        
        Scanner Lector;
        try {
            Lector = new Scanner(ArchivoMenu);
            while(Lector.hasNextLine()){
                String Partes[] = Lector.nextLine().split(" - ");
                ID = Integer.parseInt(Partes[0]);
                Nombre = Partes[1];
                Descripcion = Partes[2];
                Categoria = Partes[3];
                Tamano = Partes[4];
                Precio = Float.parseFloat(Partes[5]);
                Disponibilidad = Boolean.parseBoolean(Partes[6]);

                ModeloMenu.addRow(new Object[]{ID, Nombre, Descripcion, Categoria, Tamano, Precio, Disponibilidad});
            }
            Lector.close();
        } catch (FileNotFoundException ex) {
            System.getLogger(pnlConsultaMenu.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMenu = new javax.swing.JTable();

        setClosable(true);

        tblMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Articulo", "Nombre", "Descripcion", "Categoria", "Tamaño", "Precio", "Disponibilidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMenu;
    // End of variables declaration//GEN-END:variables
}
